---
- name: 'Start from scratch and DELETE EVERYTHING'
  hosts: 'localhost'
  gather_facts: 'no'
  become: 'false'
 
  tasks:

    - name: 'Delete all the files'
      file:
        path: "{{ item }}"
        state: 'absent'
      loop:
        - '../k3sup_installation.sh'
        - '../kubeconfig_k3sup_ha.yaml'
        - '../ssh_key_k3sup_ha'
        - '../ssh_key_k3sup_ha.pub'
